import { generalStyles } from "./GeneralStyles";
import {DarkColors as colors } from "./colors";
import { StyleSheet } from "react-native";

export const adminStyles = StyleSheet.create({
    ...generalStyles, //inherit general styles for container and others

    adminSubtitle: {
        color: colors.muted,
        fontSize: 13,
        marginBottom: 4,
    },
    adminTabRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginTop: 8,
        marginBottom: 12,
    },
    adminTabRowSpacer: {
        flex: 1,
    },
    adminPromotionRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 10,
        marginBottom: 10,
        flexWrap: "wrap",
    },
    adminPromotionToggleGroup: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    adminPromotionToggleText: {
        color: colors.text,
        fontSize: 12,
        fontWeight: "600",
    },
    adminPromotionButton: {
        backgroundColor: "#2563EB",
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 14,
    },
    adminPromotionButtonText: {
        color: "#FFFFFF",
        fontSize: 12,
        fontWeight: "700",
    },
    adminPromotionModalList: {
        maxHeight: 320,
        marginTop: 8,
        marginBottom: 12,
    },
    adminPromotionModalListContent: {
        gap: 8,
    },
    adminPromotionModalItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: 8,
        backgroundColor: colors.card,
    },
    adminPromotionModalItemText: {
        color: colors.text,
        fontSize: 12,
        fontWeight: "600",
        flexShrink: 1,
        marginRight: 8,
    },
    adminPromotionModalActions: {
        flexDirection: "row",
        justifyContent: "flex-end",
        alignItems: "center",
        gap: 10,
    },
    adminPromotionModalCancelButton: {
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 14,
        backgroundColor: colors.card,
    },
    adminPromotionModalCancelText: {
        color: colors.text,
        fontSize: 12,
        fontWeight: "700",
    },
    adminTabButton: {
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 10,
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
    },
    adminTabButtonActive: {
        backgroundColor: colors.accent,
        borderColor: colors.accent,
    },
    adminTabButtonText: {
        color: colors.text,
        fontSize: 13,
        fontWeight: "600",
    },
    adminTabButtonTextActive: {
        color: colors.background,
    },
    adminSheetContainer: {
        flex: 1,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 12,
        overflow: "visible",
        backgroundColor: colors.card,
    },
    adminSheetHeaderRow: {
        flexDirection: "row",
        backgroundColor: colors.background,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    adminSheetRow: {
        flexDirection: "row",
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    adminSheetRowOpen: {
        zIndex: 3000,
        elevation: 3000,
        position: "relative",
    },
    adminSheetContentContainer: {
        paddingBottom: 12,
    },
    adminHeaderCell: {
        width: 150,
        paddingHorizontal: 10,
        paddingVertical: 10,
        color: colors.text,
        fontWeight: "700",
        fontSize: 12,
    },
    adminHeaderCellWide: {
        width: 240,
    },
    adminReadCell: {
        width: 150,
        paddingHorizontal: 10,
        paddingVertical: 12,
        color: colors.text,
        fontSize: 12,
    },
    adminEditCell: {
        width: 150,
        paddingHorizontal: 10,
        paddingVertical: 10,
        color: colors.text,
        fontSize: 12,
        borderLeftWidth: 1,
        borderLeftColor: colors.border,
    },
    adminContactCell: {
        width: 150,
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderLeftWidth: 1,
        borderLeftColor: colors.border,
        justifyContent: "center",
        position: "relative",
    },
    adminContactCellWide: {
        width: 240,
    },
    adminContactCellReadMode: {
        backgroundColor: colors.card,
    },
    adminContactCellEditMode: {
        backgroundColor: colors.background,
        borderColor: colors.accent,
        borderWidth: 1,
    },
    adminCellActionButton: {
        position: "absolute",
        top: 2,
        right: 4,
        zIndex: 2,
        padding: 4,
    },
    adminCellActionButtonEditMode: {
        backgroundColor: colors.accent,
        borderRadius: 10,
    },
    adminContactCellText: {
        color: colors.text,
        fontSize: 12,
        paddingRight: 18,
        minHeight: 20,
        paddingTop: 8,
    },
    adminContactCellInput: {
        color: colors.text,
        fontSize: 12,
        paddingRight: 18,
        minHeight: 20,
        paddingTop: 8,
        borderBottomWidth: 1,
        borderBottomColor: colors.accent,
    },
    adminRowActionHeader: {
        width: 78,
        paddingHorizontal: 10,
        paddingVertical: 10,
        color: colors.text,
        fontWeight: "700",
        fontSize: 12,
        textAlign: "center",
        borderLeftWidth: 1,
        borderLeftColor: colors.border,
    },
    adminRowActionCell: {
        width: 78,
        alignItems: "center",
        justifyContent: "center",
        borderLeftWidth: 1,
        borderLeftColor: colors.border,
    },
    adminDeleteButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "rgba(255, 107, 107, 0.12)",
    },
    adminEditCellWide: {
        width: 230,
        paddingHorizontal: 10,
        paddingVertical: 10,
        color: colors.text,
        fontSize: 12,
        borderLeftWidth: 1,
        borderLeftColor: colors.border,
    },
    adminEditCellStatus: {
        width: 120,
        paddingHorizontal: 10,
        paddingVertical: 10,
        color: colors.text,
        fontSize: 12,
        borderLeftWidth: 1,
        borderLeftColor: colors.border,
    },
    adminKeyCol: {
        width: 230,
    },
    adminJobTitleCell: {
        width: 210,
        paddingHorizontal: 10,
        paddingVertical: 12,
        color: colors.text,
        fontWeight: "600",
        fontSize: 12,
    },
    adminCadetCellWrapper: {
        flex: 1,
        borderLeftWidth: 1,
        borderLeftColor: colors.border,
    },
    adminCadetInput: {
        paddingHorizontal: 10,
        paddingVertical: 10,
        color: colors.text,
        fontSize: 12,
        minWidth: 200,
    },
    adminAutocompleteWrapper: {
        flex: 1,
    },
    adminSuggestionList: {
        borderTopWidth: 1,
        borderTopColor: colors.border,
        backgroundColor: colors.background,
    },
    adminSuggestionItem: {
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    adminSuggestionText: {
        color: colors.text,
        fontSize: 12,
    },
    attendanceToolbarRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        gap: 12,
        marginBottom: 12,
        flexWrap: "wrap",
    },
    attendanceToolbarActions: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        flexWrap: "wrap",
    },
    attendanceAllowanceControl: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
    },
    attendanceAllowanceLabel: {
        color: colors.text,
        fontSize: 13,
        fontWeight: "600",
    },
    attendanceAllowanceInput: {
        minWidth: 72,
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.card,
        color: colors.text,
        fontSize: 13,
    },
    attendanceAllowanceInputReadOnly: {
        opacity: 0.8,
    },
    attendanceSheetRow: {
        flex: 1,
        flexDirection: "row",
    },
    attendanceFrozenColumn: {
        borderRightWidth: 1,
        borderRightColor: colors.border,
        backgroundColor: colors.card,
        zIndex: 1,
    },
    attendanceRefreshButton: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 10,
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
    },
    attendanceRefreshButtonText: {
        color: colors.text,
        fontSize: 13,
        fontWeight: "600",
    },
    attendanceNameCell: {
        width: 180,
    },
    attendanceRemainingCell: {
        width: 110,
        textAlign: "center",
    },
    attendanceRemainingValue: {
        fontWeight: "700",
    },
    attendanceDateCell: {
        width: 90,
        textAlign: "center",
    },
    attendanceStatusCell: {
        borderLeftWidth: 1,
        borderLeftColor: colors.border,
    },
    attendanceCellButton: {
        justifyContent: "center",
        alignItems: "center",
    },
    attendanceCellReadOnly: {
        opacity: 0.8,
    },
    attendanceCellSaving: {
        opacity: 0.55,
    },
    attendanceStatusValue: {
        fontWeight: "700",
        color: colors.text,
        textAlignVertical: "center",
    },
});