const EVENT_MAKING_PERMISSION = "Event Making";
const FILE_UPLOADING_PERMISSION = "File Uploading";
const ATTENDANCE_EDITING_PERMISSION = "Attendance Editing";
const CREATE_ACCOUNTS_PERMISSION = "Account Creation";

export const DEFAULT_PERMISSIONS_MAP = new Map<string, boolean>([
    [EVENT_MAKING_PERMISSION, false],
    [FILE_UPLOADING_PERMISSION, false],
    [ATTENDANCE_EDITING_PERMISSION, false],
    [CREATE_ACCOUNTS_PERMISSION, false]
]);

export const PERMISSIONS = {
    EVENT_MAKING: EVENT_MAKING_PERMISSION,
    FILE_UPLOADING: FILE_UPLOADING_PERMISSION,
    ATTENDANCE_EDITING: ATTENDANCE_EDITING_PERMISSION,
    CREATE_ACCOUNTS: CREATE_ACCOUNTS_PERMISSION
}
    

