const EVENT_MAKING_PERMISSION = "Event Making";
const FILE_UPLOADING_PERMISSION = "File Uploading";
const ATTENDANCE_EDITING_PERMISSION = "Attendance Editing";

export const PERMISSIONS = {
    EVENT_MAKING: EVENT_MAKING_PERMISSION,
    FILE_UPLOADING: FILE_UPLOADING_PERMISSION,
    ATTENDANCE_EDITING: ATTENDANCE_EDITING_PERMISSION,
}